# Generated by Django 4.0.3 on 2022-03-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('urn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('open_date', models.CharField(max_length=200, null=True)),
                ('close_date', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('school_website', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200, verbose_name='Date of birth')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school')),
            ],
        ),
    ]
