# Generated by Django 4.0.3 on 2022-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_school_phone_number_alter_school_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.IntegerField(),
        ),
    ]
